apiVersion: v1
kind: Service
metadata:
  name: cudo-flash
  labels:
    app: cudo-flash
spec:
  type: LoadBalancer
  selector:
    app: cudo-flash
  ports:
  - port: 2137
    name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cudo-flash
spec:
  selector:
    matchLabels:
      app: cudo-flash
  replicas: 1
  template:
    metadata:
      labels:
        app: cudo-flash
    spec:
      containers:
        - image: nmarcin92/cudoflash:0.0.1
          imagePullPolicy: Always
          name: cudoflash-app